# BASE IMAGE FROM WHICH TO EXTEND.
FROM python:3.7-alpine
MAINTAINER Anubhav Sidhu

# UPDATE THE BASE IMAGE.
RUN apk update

# SET PYTHON UNBUFFERED ENV VARIABLE.
ENV PYTHONUNBUFFERED 1

# INSTALL PYTHON DEPENDENCIES.

# CREATE APP DIRECTORY AND SET WORKDIR.
RUN mkdir /application
WORKDIR /application

# CREATE VIRTUAL ENV.

# COPY DEPENDENCIES.TXT AND INSTALL ALL THE DEPENDENCIES.
ADD dependencies.txt dependencies.txt 
RUN pip install -r dependencies.txt

# COPY SOURCE CODE TO THE APPLICATION DIRECTORY.
ADD ./application /application

# CREATING A USER TO RUN OUR APPLICATION INSIDE THE CONTAINER.
RUN adduser -D app_user
USER app_user

# EXPOSE PORT INSIDE CONTAINER TO OUTSIDE WORLD.
EXPOSE 9000

# DEFAULT COMMAND THAT GETS EXECUTED WHEN AN CONTAINER IS SPWANED.